language: php

php:
  - '7.1'
branches:
  only:
    master
services:
  - mysql
before_install:
  - mysql -e 'CREATE DATABASE picnic';
script: 
  - phpunit ./admin/testharness/unit
  - phpunit ./admin/testharness/system
  
